reviewers: 1
docker:
  builds:
    - path: .
      dockerfile: Dockerfile
      docker_repo: balena/pinejs-sut
      publish: false
npm:
  run: true
  platforms:
    - name: linux
      os: alpine
      architecture: x86_64
      node_versions:
        - "14"
        - "16"
        - "18"
