version: "2.1"
services:
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: postgres
    ports:
      - "5432"
      - "5431:5432"
    networks:
      - internal
  sut:
    image: balena/pinejs-sut:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: sut
    depends_on:
      - postgres
    environment:
      LOGLEVEL: error
      API_HOST: 127.0.0.1 
      DATABASE_URL: postgres://docker:docker@postgres:5432/postgres 
      DEBUG: 
      PORT: 80 
    networks:
      - internal

networks:
  internal:
